from . import gym_agreement
from . import gym_checkin
from . import gym_tablet_attempt
from . import pos_config
from . import pos_order
from . import product_template
from . import res_config_settings
from . import res_partner
from . import sale_order
