# Container's own (delivery method customisation):
from . import account_move
from . import account_move_direct_sale
from . import loadsheet_category
from . import product_shop_orderpoint
from . import product_template
from . import res_company
from . import res_config_settings
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import stock_move
from . import stock_picking
from . import stock_picking_type
# Absorbed from centric_auto_lot_assignment:
from . import res_config_settings_auto_lot
from . import stock_move_auto_lot
from . import stock_picking_auto_lot
# Absorbed from centric_backorder_toggle:
from . import res_company_backorder
from . import res_config_settings_backorder
from . import stock_picking_backorder
# Absorbed from centric_expiry_warning:
from . import stock_picking_expiry
# Absorbed from centric_negative_stock_lot:
from . import stock_lot
from . import stock_move_negative
from . import stock_move_line
from . import stock_picking_negative_expiry
# Absorbed from not_delivered_delivery_flow:
from . import sale_order_not_delivered
from . import stock_picking_not_delivered
